### ISSUE TITLE
What's the status?

### ISSUE THREAD

**Issue by mcandre** [picoriley/PebbleGameboyEmulator#1]

**Comment by picoriley** [comment]
Not happening, unfortunately. I made this repo before I realized that, although the emulator would be possible, you'd never be able to fit a ROM into the limited amount of memory they give you. Sorry about that!

**Comment by mcandre** [comment]
Would there be enough room on a Pebble Time? It has double the memory, it's
just waiting for an OS update to make it available.

On Friday, August 7, 2015, Anthony Cloudy <notifications@github.com> wrote:

> Not happening, unfortunately. I made this repo before I realized that,
> although the emulator would be possible, you'd never be able to fit a ROM
> into the limited amount of memory they give you. Sorry about that!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/picoriley/PebbleGameboyEmulator/issues/1#issuecomment-128879249>
> .
>


-- 
Cheers,
Andrew

**Comment by picoriley** [comment]
Possibly, I haven't looked at the specs yet, and I only have access to the original pebble. I won't be able to do it, but you're more than welcome to fork this repo and give it a shot if you'd like! :D
